name: subsplit

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  subsplit:
    name: Split Packages (${{ matrix.package.local_path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          # Dev
          - local_path: 'protocol-generator'
            split_repository: 'protocol-generator'
          # Contracts
          - local_path: 'contracts/hydrator-contracts'
            split_repository: 'hydrator-contracts'
          - local_path: 'contracts/router-contracts'
            split_repository: 'router-contracts'
          # Kernel
          - local_path: 'dispatcher'
            split_repository: 'dispatcher'
          - local_path: 'hydrator-jms'
            split_repository: 'hydrator-jms'
          - local_path: 'kernel'
            split_repository: 'kernel'
          - local_path: 'protocol'
            split_repository: 'protocol'
          - local_path: 'router'
            split_repository: 'router'
          - local_path: 'server-react'
            split_repository: 'server-react'
          - local_path: 'server'
            split_repository: 'server'
          # RPC
          # - RPC: Metadata
          - local_path: 'rpc/meta'
            split_repository: 'rpc'
          # - RPC: Contracts
          - local_path: 'rpc/contracts/rpc-codec-contracts'
            split_repository: 'rpc-codec-contracts'
          - local_path: 'rpc/contracts/rpc-message-contracts'
            split_repository: 'rpc-message-contracts'
          - local_path: 'rpc/contracts/rpc-message-factory-contracts'
            split_repository: 'rpc-message-factory-contracts'
          # - RPC: Implementations
          - local_path: 'rpc/rpc-codec-jsonrpc'
            split_repository: 'rpc-codec-jsonrpc'
          - local_path: 'rpc/rpc-message'
            split_repository: 'rpc-message'
          - local_path: 'rpc/rpc-message-factory'
            split_repository: 'rpc-message-factory'
    steps:
      - uses: actions/checkout@v4

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package.split_repository }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'php-lsp'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'php-lsp'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"
