name: subsplit

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  subsplit:
    name: Split Packages (${{ matrix.package.local_path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          # Bridge
          - local_path: 'bridge/hydrator-type-lang'
            split_repository: 'hydrator-type-lang'
          - local_path: 'bridge/server-driver-react'
            split_repository: 'server-driver-react'
          # Contracts
          - local_path: 'contracts/hydrator-contracts'
            split_repository: 'hydrator-contracts'
          - local_path: 'contracts/router-contracts'
            split_repository: 'router-contracts'
          - local_path: 'contracts/rpc-codec-contracts'
            split_repository: 'rpc-codec-contracts'
          - local_path: 'contracts/rpc-message-contracts'
            split_repository: 'rpc-message-contracts'
          - local_path: 'contracts/rpc-message-factory-contracts'
            split_repository: 'rpc-message-factory-contracts'
          - local_path: 'contracts/server-contracts'
            split_repository: 'server-contracts'
          # Components
          - local_path: 'components/dispatcher'
            split_repository: 'dispatcher'
          - local_path: 'components/kernel'
            split_repository: 'kernel'
          - local_path: 'components/protocol'
            split_repository: 'protocol'
          - local_path: 'components/protocol-generator'
            split_repository: 'components/protocol-generator'
          - local_path: 'components/router'
            split_repository: 'router'
          - local_path: 'components/rpc-codec-jsonrpc'
            split_repository: 'rpc-codec-jsonrpc'
          - local_path: 'components/rpc-message'
            split_repository: 'rpc-message'
          - local_path: 'components/rpc-message-factory'
            split_repository: 'rpc-message-factory'
          - local_path: 'components/server'
            split_repository: 'server'
    steps:
      - uses: actions/checkout@v4

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package.split_repository }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'php-lsp'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'php-lsp'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"
